influencer/Controllers/ManageRoleController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using System.Threading.Tasks;

namespace influencer.Controllers
{
    [Authorize(Roles = "Admin")]
    public class ManageRoleController : Controller
    {
        private readonly RoleManager<IdentityRole> _roleManager;

        public ManageRoleController(RoleManager<IdentityRole> roleManager)
        {
            _roleManager = roleManager;
        }

        public IActionResult Index()
        {
            var roles = _roleManager.Roles.ToList();
            return View(roles);
        }

        [HttpGet]
        public IActionResult AddRole()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddRole(string name)
        {
            if (string.IsNullOrEmpty(name)) return NotFound();
            var role = new IdentityRole(name);
            var result = await _roleManager.CreateAsync(role);
            if (result.Succeeded) return RedirectToAction("Index");

            foreach (var error in result.Errors)
            {
                ModelState.AddModelError(string.Empty, error.Description);
            }

            return View(role);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteRole(string id)
        {
            if (string.IsNullOrEmpty(id)) return NotFound();
            var role = await _roleManager.FindByIdAsync(id);
            if (role == null) return NotFound();
            await _roleManager.DeleteAsync(role);

            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> EditRole(string id)
        {
            if (string.IsNullOrEmpty(id)) return NotFound();

            var role = await _roleManager.FindByIdAsync(id);

            if (role == null) return NotFound();

            return View(role);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditRole(string id, string name)
        {
            if (string.IsNullOrEmpty(id) || string.IsNullOrEmpty(name)) return NotFound();

            var role = await _roleManager.FindByIdAsync(id);
            if (role == null) return NotFound();
            role.Name = name;
            var result = await _roleManager.UpdateAsync(role);
            if (result.Succeeded) return RedirectToAction("Index");

            foreach (var error in result.Errors)
            {
                ModelState.AddModelError(string.Empty, error.Description);
            }

            return View(role);
        }
    }
}

influencer/Views/ManageRole/AddRole.cshtml
@model Microsoft.AspNetCore.Identity.IdentityRole
@{
    ViewData["Title"] = "AddRole";
}
<div class="container">
    <main role="main" class="pb-3">

        <div class="row">
            <div class="col-md-4">
                <h1>AddRole</h1>

                <form asp-controller="ManageRole" asp-action="AddRole" method="post">
                    <div asp-validation-summary="ModelOnly"></div>
                    <div class="form-group">
                        <label class="control-label">Name :</label>
                        <input class="form-control" asp-for="Name" />
                    </div>

                    <button class="btn btn-danger" type="submit">Submit</button>
                </form>
            </div>
        </div>
    </main>

</div>

influencer/Views/ManageRole/EditRole.cshtml
@model Microsoft.AspNetCore.Identity.IdentityRole
@{
    ViewData["Title"] = "EditRole";
}
<div class="container">
    <main role="main" class="pb-3">

        <div class="row">
            <div class="col-md-4">
                <h1>EditRole</h1>

                <form asp-controller="ManageRole" asp-action="EditRole" asp-route-id="@Model.Id" method="post">
                    <div asp-validation-summary="ModelOnly"></div>
                    <div class="form-group">
                        <label class="control-label">Name :</label>
                        <input class="form-control" asp-for="Name" />
                    </div>

                    <button class="btn btn-danger" type="submit">Submit</button>
                </form>
            </div>
        </div>
    </main>

</div>

influencer/Views/ManageRole/Index.cshtml
@model List<Microsoft.AspNetCore.Identity.IdentityRole>
@{
    ViewData["Title"] = "Index";
}

<div class="container">
    <main role="main" class="pb-3">

        <div class="row">
            <div class="col-md-10">
                <a asp-controller="ManageRole" asp-action="AddRole" class="btn btn-danger">Add role</a>

                @if (!Model.Any())
                {
                    <h1>مقامی یافت نشد</h1>
                }
                else
                {
                    for (int i = 0; i < Model.Count; i++)
                    {
                        <div class="card mt-2">
                            <div class="card-body">
                                Role Name : <b>@Model[i].Name</b>
                            </div>
                            <div class="card-footer">
                                <form asp-controller="ManageRole" asp-action="DeleteRole" method="post" asp-route-id="@Model[i].Id">

                                    <a asp-controller="ManageRole" asp-action="EditRole" asp-route-id="@Model[i].Id"
                                       class="btn btn-danger">Edit</a>

                                    <button type="submit" class="btn btn-danger">Delete</button>
                                </form>
                            </div>
                        </div>
                    }
                }
            </div>
        </div>
    </main>

</div>