influencer/ViewModels/Advertise/AdvertiseViewModel.cs
using influencer.Common;
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace influencer.ViewModels.Advertise
{
    public class AdvertiseViewModel : EditImageViewModel
    {
        public Guid Id { get; set; }
        [Required]
        public Int16 Categories { get; set; }
        [Required]
        [StringLength(100)]
        public string Title { get; set; }
        [StringLength(500)]
        public string Contents { get; set; }
        [Required]
        
        [Display(Name = "Order")]
        public Int16 OrderAdvertise { get; set; }
        [Display(Name = "Followers Count")]
        public int CntFollowers { get; set; }
        [Display(Name = "Viewers Count")]
        public int CntViewers { get; set; }
        public Int16 Fame { get; set; }
        [Required]
        [DataType(DataType.DateTime)]
        public DateTime DateTime { get; set; }
    }
    public class UploadImageViewModel
    {
        [Display(Name = "Picture")]
        [DataType(DataType.Upload)]
        [AllowedExtensions(new string[] { ".jpg", ".jpeg", ".png", ".gif", ".bmp" })]
        //[FileExtensions(Extensions = "jpg,png,gif,jpeg,bmp")]
        public IFormFile AdvPicture { get; set; }
    }
    public class EditImageViewModel : UploadImageViewModel
    {
        public int Id { get; set; }
        public string ExistingImage { get; set; }
    }
}

influencer/Controllers/AdvertiseController.cs
using Domain.Contracts;
using Domain.Entities;
using Domain.Entities.Context;
using influencer.Common;
using influencer.ViewModels.Advertise;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Drawing.Imaging;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace influencer.Controllers
{
    [Authorize(Roles = "Blogger,Admin")]
    public class AdvertiseController : Controller
    {
        private readonly IAdvertiseRepository _advertiseRepository;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IWebHostEnvironment _webHostEnvironment;
        public AdvertiseController(IAdvertiseRepository advertiseRepository, UserManager<ApplicationUser> userManager, IWebHostEnvironment webHostEnvironment)
        {
            _advertiseRepository = advertiseRepository;
            _userManager = userManager;
            _webHostEnvironment = webHostEnvironment;
        }
        /************************************************************************************/
        ////Display all Advertises
        //Method to display all Advertises which is received from 'GetAllAdvertises' method

        public IActionResult Index()
        {
            try
            {
                if (User.IsInRole("Admin"))
                {
                    List<Advertise> Advertise = _advertiseRepository.FindAll().OrderBy(m => m.OrderAdvertise).ToList();
                    return View(Advertise);
                }
                else
                {
                    string loggedInUserId = _userManager.GetUserId(User);
                    List<Advertise> Advertise = _advertiseRepository.FindByCondition(m => m.UserId == loggedInUserId).OrderBy(m => m.OrderAdvertise).ToList();
                    return View(Advertise);
                }
            }
            catch (Exception e)
            {
                return View();
            }
        }
        /************************************************************************************/
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var advertise = await _advertiseRepository.FindByCondition(m => m.Id == id).FirstOrDefaultAsync();
            if (advertise == null)
            {
                return NotFound();
            }

            return View(advertise);
        }

        // GET: advertise/Create
        [HttpGet]
        public IActionResult Create()
        {
            ViewBag.RowsAdv = _advertiseRepository.FindByCondition(m => m.UserId == _userManager.GetUserId(User)).FirstOrDefault();
            return View();
        }

        // POST: advertise/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(AdvertiseViewModel advertise)
        {
            if (ModelState.IsValid)
            {
                Advertise advertise1 = new Advertise
                {
                    DateTime = DateTime.Now,
                    AdvPicture = UploadedFile(advertise),
                    UserId = _userManager.GetUserId(User),
                    Title = advertise.Title,
                    Categories = advertise.Categories,
                    Contents = advertise.Contents,
                    CntFollowers = advertise.CntFollowers,
                    CntViewers = advertise.CntViewers,
                    Fame = advertise.Fame,
                    OrderAdvertise = advertise.OrderAdvertise
                };
                await _advertiseRepository.Create(advertise1);
                return RedirectToAction(nameof(Index));
            }
            return View();
        }

        private string UploadedFile(AdvertiseViewModel advertise)
        {
            string uniqueFileName = null;

            if (advertise.AdvPicture != null)
            {
                string uploadsFolder = Path.Combine(_webHostEnvironment.WebRootPath, "Uploads");
                uniqueFileName = Guid.NewGuid().ToString() + "_" + advertise.AdvPicture.FileName;
                string filePath = Path.Combine(uploadsFolder, uniqueFileName);

                IFormFile file = advertise.AdvPicture;
                var image = Image.FromStream(file.OpenReadStream());
                image = FixedSizeImage.FixedSize(image, 800, 600);
                using var imageStream = new MemoryStream();
                image.Save(imageStream, ImageFormat.Jpeg);
                var imageBytes = imageStream.ToArray();
                using (var stream = new FileStream(filePath, FileMode.Create, FileAccess.Write, FileShare.Write, 4096))
                {
                    stream.Write(imageBytes, 0, imageBytes.Length);
                }
            }
            return uniqueFileName;
        }

        // GET: advertise/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var advertise = await _advertiseRepository.FindByCondition(m => m.Id == id).FirstOrDefaultAsync();
            var advertiseViewModel = new AdvertiseViewModel()
            {
                Id = advertise.Id,
                Title = advertise.Title,
                Contents = advertise.Contents,
                Categories = advertise.Categories,
                CntFollowers = advertise.CntFollowers,
                CntViewers = advertise.CntViewers,
                DateTime = advertise.DateTime,
                Fame = advertise.Fame,
                OrderAdvertise = advertise.OrderAdvertise,
                ExistingImage = advertise.AdvPicture
            };

            if (advertise == null)
            {
                return NotFound();
            }
            return View(advertiseViewModel);
        }

        // POST: advertise/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[ValidateAntiForgeryToken]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, AdvertiseViewModel advertise)
        {
            if (id != advertise.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                var adv = await _advertiseRepository.FindByCondition(m => m.Id == advertise.Id).FirstOrDefaultAsync();
                adv.Title = advertise.Title;
                adv.Contents = advertise.Contents;
                adv.Categories = advertise.Categories;
                adv.CntFollowers = advertise.CntFollowers;
                adv.CntViewers = advertise.CntViewers;
                //adv.DateTime = advertise.DateTime;
                adv.Fame = advertise.Fame;
                adv.OrderAdvertise = advertise.OrderAdvertise;
                if (advertise.AdvPicture != null)
                {
                    if (advertise.ExistingImage != null)
                    {
                        string filePath = Path.Combine(_webHostEnvironment.WebRootPath, "Uploads", advertise.ExistingImage);
                        System.IO.File.Delete(filePath);
                    }

                    adv.AdvPicture = UploadedFile(advertise);
                }
                await _advertiseRepository.Update(adv);
                return RedirectToAction(nameof(Index));
            }
            return View(advertise);
        }
        [HttpPost]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var advertise = await _advertiseRepository.FindByCondition(m => m.Id == id).FirstOrDefaultAsync();
            var CurrentImage = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\Uploads", advertise.AdvPicture);
            Advertise DelAdv = await _advertiseRepository.Delete(advertise);
            //if (DelAdv.Equals==null)
            //{
            if (System.IO.File.Exists(CurrentImage))
            {
                System.IO.File.Delete(CurrentImage);
            }
            //}
            return Json(true);
        }

        private bool advertiseExists(Guid id)
        {
            return _advertiseRepository.FindByCondition(e => e.Id == id).Any();
        }
        [AllowAnonymous]
        public IActionResult AllAdvertise()
        {
            try
            {
                List<AdvertiseDo> Advertise = _advertiseRepository.SelectAllWithInsta().ToList();
                return View(Advertise);
            }
            catch (Exception e)
            {
                return View();
            }
        }
    }
}

influencer/Views/Advertise/AllAdvertise.cshtml
@using Domain.Entities;
@inject IViewLocalizer Localizer
@model IEnumerable<Domain.Entities.AdvertiseDo>
@{
    ViewData["Title"] = @Localizer["AllAdvertise"];
}
<div class="container">
    <main role="main" class="pb-3 portfolio">
        <div class="row">
            <div class="col-md-10 col-sm-8 col-7">
                <h1>@Localizer["AllAdvertise"]</h1>
            </div>
            <div class="col-md-2 col-sm-4 col-5">
                <a class="btn btn-secondary" asp-action="Index" asp-controller="Home">@Localizer["Back"]</a>
            </div>
        </div>
        <div class="row" data-aos="fade-right" data-aos-delay="100">
            <div class="col-lg-12 d-flex justify-content-center">
                <ul id="portfolio-flters">
                    <li data-filter="*" class="filter-active">@Localizer["All"]</li>
                    <li data-filter=".filter-ladies">@Localizer["ladies"]</li>
                    <li data-filter=".filter-health">@Localizer["health"]</li>
                    <li data-filter=".filter-fact"> @Localizer["fact"]</li>
                    <li data-filter=".filter-successAndMotivation">@Localizer["successAndMotivation"]</li>
                    <li data-filter=".filter-sports">@Localizer["sports"]</li>
                    <li data-filter=".filter-artandMusic">@Localizer["artandMusic"]</li>
                    <li data-filter=".filter-lifestyle">@Localizer["lifestyle"]</li>
                    <li data-filter=".filter-foods">@Localizer["foods"]</li>
                    <li data-filter=".filter-funny">@Localizer["funny"]</li>
                    <li data-filter=".filter-teaching">@Localizer["teaching"]</li>
                </ul>
            </div>
        </div>
        <div class="row portfolio-container" data-aos="fade-right" data-aos-delay="200" style="position: relative; height: 855px;">
            @foreach (AdvertiseDo advertise in Model)
            {
                var insta = (advertise.InstagramPage == "") ? "http://www.instagram.com" : advertise.InstagramPage;
                var cat = "";
                var catName = "";
                @switch (@advertise.Categories)
                {
                    case 1:
                        {
                            cat = Localizer["ladies"].Value;
                            catName = "ladies";
                            break;
                        }
                    case 2:
                        {
                            cat = Localizer["health"].Value;
                            catName = "health";
                            break;
                        }
                    case 3:
                        {
                            cat = Localizer["fact"].Value;
                            catName = "fact";
                            break;
                        }
                    case 4:
                        {
                            cat = Localizer["successAndMotivation"].Value;
                            catName = "successAndMotivation";
                            break;
                        }
                    case 5:
                        {
                            cat = Localizer["sports"].Value;
                            catName = "sports";
                            break;
                        }
                    case 6:
                        {
                            cat = Localizer["artandMusic"].Value;
                            catName = "artandMusic";
                            break;
                        }
                    case 7:
                        {
                            cat = Localizer["lifestyle"].Value;
                            catName = "lifestyle";
                            break;
                        }
                    case 8:
                        {
                            cat = Localizer["foods"].Value;
                            catName = "foods";
                            break;
                        }
                    case 9:
                        {
                            cat = Localizer["funny"].Value;
                            catName = "funny";
                            break;
                        }
                    case 10:
                        {
                            cat = Localizer["teaching"].Value;
                            catName = "teaching";
                            break;
                        }
                }
                <div class="col-lg-3 col-md-4 portfolio-item filter-@catName">
                    <div class="portfolio-wrap">
                        <a href="~/Uploads/@advertise.AdvPicture" data-gallery="portfolioGallery" class="portfolio-lightbox" title="@advertise.Title">
                            <img src="~/Uploads/@advertise.AdvPicture" class="img-fluid" alt="">
                        </a>
                        <div class="portfolio-info">
                            <h4>@advertise.Title</h4>
                            <p>
                                @cat
                            </p>
                            <div class="portfolio-links">
                                <a href="@insta" target="_blank" data-bs-toggle="tooltip" title="Blogger Instagram">
                                    <i class="bx bxl-instagram"></i>
                                </a>
                                <a href="#" data-bs-toggle="tooltip" title="Viewers Count=@advertise.CntViewers">
                                    <span style="font-size:12px">@advertise.CntViewers</span>
                                    <i class="bx bx-show"></i>
                                </a>
                                <a href="#" data-bs-toggle="tooltip" title="Follower Count=@advertise.CntFollowers">
                                    <span style="font-size:12px">@advertise.CntFollowers</span>
                                    <i class="bx bxs-show"></i>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>
    </main>
</div>
@section Scripts{
    <script>
        $(function () {
            $(".portfolio-wrap .portfolio-info").click(function () {
                $(this).parents(".portfolio-wrap").find("a.portfolio-lightbox img").click()
            });
        })
    </script>
}

influencer/Views/Advertise/Delete.cshtml
@model Domain.Entities.Advertise

@{
    ViewData["Title"] = "Delete";
}
<div class="container">
    <main role="main" class="pb-3">
        <h1>Delete</h1>
        <h3>Are you sure you want to delete this?</h3>
        <div>
            <h4>Advertise</h4>
            <hr />
            <dl class="row">
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.Title)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.Title)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.Categories)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.Categories)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.CntFollowers)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.CntFollowers)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.CntViewers)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.CntViewers)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.Fame)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.Fame)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.DateTime)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.DateTime)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.AdvPicture)
                </dt>
                <dd class="col-sm-10">
                    <img id="imageresource" src="~/Uploads/@Model.AdvPicture" width="200" asp-append-version="true" />
                </dd>
            </dl>
            <form asp-action="Delete">
                <input type="hidden" asp-for="Id" />
                <input type="submit" value="Delete" class="btn btn-danger" /> |
                <a class="btn btn-secondary" asp-action="Index">Back to List</a>
            </form>
        </div>
    </main>
</div>

influencer/Views/Advertise/Index.cshtml
@model IEnumerable<Domain.Entities.Advertise>

@{
    ViewData["Title"] = "Index";
}
<div class="container">
    <main role="main" class="pb-3">
        <div class="row">
            <div class="col-md-10 col-sm-8 col-7">
                <h1>All Advertise</h1>
            </div>
            <div class="col-md-2 col-sm-4 col-5">
                <p>
                    <a asp-action="Create" class="btn btn-danger"><i class="bi-plus"></i>Create New</a>
                </p>
            </div>
        </div>
        <table class="table">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.Title)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.CntFollowers)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.CntViewers)
                    </th>
                    <th title="Just gold and silver members"  data-bs-toggle="tooltip">
                        @Html.DisplayNameFor(model => model.Fame)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Categories)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.OrderAdvertise)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.AdvPicture)
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @if (Model != null)
                {
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Title)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.CntFollowers)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.CntViewers)
                            </td>
                            <td title="Just gold and silver members" data-bs-toggle="tooltip">
                                @switch (@item.Fame)
                                {
                                    case 1:
                                        {
                                            <p>⭐</p>
                                            break;
                                        }
                                    case 2:
                                        {
                                            <p>⭐⭐</p>

                                            break;
                                        }
                                    case 3:
                                        {
                                            <p>⭐⭐⭐</p>
                                            break;
                                        }
                                    case 4:
                                        {
                                            <p>⭐⭐⭐⭐</p>

                                            break;
                                        }
                                    case 5:
                                        {
                                            <p>⭐⭐⭐⭐⭐</p>
                                            break;
                                        }
                                }
                            </td>
                            <td>
                                @switch (@item.Categories)
                                {
                                    case 1:
                                        {
                                            <p>Ladies</p>
                                            break;
                                        }
                                    case 2:
                                        {
                                            <p>Health</p>

                                            break;
                                        }
                                    case 3:
                                        {
                                            <p>Fact</p>
                                            break;
                                        }
                                    case 4:
                                        {
                                            <p>Success And Motivation</p>
                                            break;
                                        }
                                    case 5:
                                        {
                                            <p>Sports</p>
                                            break;
                                        }
                                    case 6:
                                        {
                                            <p>Art and Music</p>
                                            break;
                                        }
                                    case 7:
                                        {
                                            <p>Lifestyle</p>
                                            break;
                                        }
                                    case 8:
                                        {
                                            <p>Foods</p>
                                            break;
                                        }
                                    case 9:
                                        {
                                            <p>Funny</p>
                                            break;
                                        }
                                    case 10:
                                        {
                                            <p>Teaching</p>
                                            break;
                                        }
                                }
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.OrderAdvertise)
                            </td>
                            <td>
                                <a href="#" class="pop">
                                    <img src="~/Uploads/@item.AdvPicture" class="rounded-circle" height="40" width="40" asp-append-version="true" />
                                </a>
                            </td>
                            <td>
                                <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-outline-danger btn-sm" title="@item.Title Edit"><i class="bi-pencil"></i></a> |
                                <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-outline-danger btn-sm" title="@item.Title Details"><i class="bi-list-task"></i></a> |
                                <a data-id="@item.Id" data-name="@item.Title" title="@item.Title Delete" class="btn btn-outline-danger btn-sm delete-adv" data-bs-toggle="modal" data-bs-target="#DelModal"><i class="bi-trash"></i></a>
                            </td>
                        </tr>
                    }
                }
            </tbody>
        </table>
    </main>
</div>
<!-- Creates the bootstrap modal where the image will appear -->
<div class="modal fade" id="imagemodal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                @*<button type="button" class="close btn" data-bs-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>*@
                <h4 class="modal-title" id="myModalLabel">Image preview</h4>
            </div>
            <div class="modal-body" style="text-align: center;">
                <img src="" id="imagepreview" style="width: 400px; height: 264px;">
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-bs-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>
<!-- Modal -->
<div class="modal" id="DelModal" tabindex="-1" role="dialog" aria-labelledby="DelModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="DelModalLabel">Delete</h5>
                <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                Are You Sure Delete
                <b><span id="advName"></span></b>
                ?
                <input id="advId" name="advId" type="hidden" />
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="button" class="btn btn-danger" id="delete-to-server">Delete</button>
            </div>
        </div>
    </div>
</div>
@section Scripts{
    <script>
        $(".pop").on("click", function () {
            var img = $(this).find('img.rounded-circle');
            $('#imagepreview').attr('src', img.attr('src')); // here asign the image to the modal when the user click the enlarge link
            $('#imagemodal').modal('show'); // imagemodal is the id attribute assigned to the bootstrap modal, then i use the show function
        });
         $(document).on("click", ".delete-adv", function () {
                var myadvId = $(this).data('id');
                $(".modal-body #advId").val(myadvId);
                var myadvName = $(this).data('name');
                $(".modal-body #advName").text(myadvName);

                // As pointed out in comments,
                // it is unnecessary to have to manually call the modal.
                // $('#addBookDialog').modal('show');
            });
            $("#delete-to-server").click(function () {
                 $.ajax({
                        type: 'post',
                        url: '@Url.Action("DeleteConfirmed", "Advertise")',
                        data: {
                            id: $('#advId').val()
                        },
                         success: function (e) {
                             if (e == true) {
                                 id = $('#advId').val();
                                 $('[data-id="' + id + '"]').parents("tr").remove();
                                 $('[data-bs-dismiss="modal"]').click();
                                 alert('Delete Success');
                            }
                            else {
                             alert('Do Not Delete');
                            }
                        }
                    });
            });
    </script>
}