influencer/ViewModels/SiteSetting/RoleValidationGuidViewModel.cs
using System;

namespace influencer.ViewModels.SiteSetting
{
    public class RoleValidationGuidViewModel
    {
        public string Value { get; set; }
        public DateTime? LastTimeChanged { get; set; }
    }
}

influencer/Controllers/SiteSettingController.cs
using Domain.Contracts;
using Domain.Entities;
using influencer.ViewModels.SiteSetting;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Memory;
using System;
using System.Collections.Generic;
using System.Linq;

namespace influencer.Controllers
{
    [Authorize(Roles = "Admin")]
    public class SiteSettingController : Controller
    {
        private readonly ISiteSettingRepository _siteSettingRepository;
        private readonly IMemoryCache _memoryCache;

        public SiteSettingController(ISiteSettingRepository siteSettingRepository, IMemoryCache memoryCache)
        {
            _siteSettingRepository = siteSettingRepository;
            _memoryCache = memoryCache;
        }


        public IActionResult Index()
        {
            List<SiteSetting> model = _siteSettingRepository.FindAll().ToList();
            return View(model);
        }

        [HttpGet]
        public IActionResult RoleValidationGuid()
        {
            var roleValidationGuidSiteSetting =
                _siteSettingRepository.FindByCondition(t => t.Key == "RoleValidationGuid").FirstOrDefault();

            var model = new RoleValidationGuidViewModel()
            {
                Value = roleValidationGuidSiteSetting?.Value,
                LastTimeChanged = roleValidationGuidSiteSetting?.LastTimeChanged
            };

            return View(model);
        }

        [HttpPost]
        public IActionResult RoleValidationGuid(RoleValidationGuidViewModel model)
        {
            var roleValidationGuidSiteSetting =
                _siteSettingRepository.FindByCondition(t => t.Key == "RoleValidationGuid").FirstOrDefault();

            if (roleValidationGuidSiteSetting == null)
            {
                _siteSettingRepository.Create(new SiteSetting()
                {
                    Key = "RoleValidationGuid",
                    Value = Guid.NewGuid().ToString(),
                    LastTimeChanged = DateTime.Now
                });
            }
            else
            {
                roleValidationGuidSiteSetting.Value = Guid.NewGuid().ToString();
                roleValidationGuidSiteSetting.LastTimeChanged = DateTime.Now;
                _siteSettingRepository.Update(roleValidationGuidSiteSetting);
            }
            _memoryCache.Remove("RoleValidationGuid");

            return RedirectToAction("Index");
        }

    }
}

influencer/Views/SiteSetting/Index.cshtml
@model List<Domain.Entities.SiteSetting>
@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>
<div class="btn-group mt-4 mb-4">
    <a asp-action="RoleValidationGuid" class="btn btn-danger">RoleValidationGuid</a>
</div>


@if (!Model.Any())
{
    <h2>No setting found</h2>
}
else
{
    for (int i = 0; i < Model.Count; i++)
    {
        <div class="card mt-2">
            <div class="card-header">
                SiteSetting Key : <b>@Model[i].Key</b>
            </div>
            <div class="card-body">
                SiteSetting Value : <b>@Model[i].Value</b>
            </div>
            <div class="card-footer">
                Last Time Value Changed = @Model[i].LastTimeChanged
            </div>
        </div>
    }
}

influencer/Views/SiteSetting/RoleValidationGuid.cshtml
@model influencer.ViewModels.SiteSetting.RoleValidationGuidViewModel
@{
    ViewData["Title"] = "RoleValidationGuid";
}

<h1>RoleValidationGuid</h1>

<form asp-controller="SiteSetting" asp-action="RoleValidationGuid" method="post">
    <div asp-validation-summary="ModelOnly"></div>

    <div class="form-group">
        <label class="control-label" asp-for="@Model.Value"></label>
        <input readonly="readonly" class="form-control" asp-for="@Model.Value" />
    </div>
    <div class="form-group">
        <label class="control-label" asp-for="@Model.LastTimeChanged"></label>
        <input readonly="readonly" class="form-control" asp-for="@Model.LastTimeChanged" />
    </div>

    <button class="btn btn-danger" type="submit">Generate New Guid</button>
</form>